services:
  # container name 
  backend:
    build: ./backend
    environment:
      - PORT=7000
    ports:
      - 8000:7000
    env_file:
      - ./backend/.env
    

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
  
